Adding HTTP2, ssl certificate and update install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,10 +1,91 @@
 #!/bin/bash
-SetColor='\033[0;32m'
+SuccessColor='\033[0;32m'
+ErrorColor='\033[0;31m'
 EndColor='\033[0m'
 
 cp ./.env_local.example ./.env
 
-echo -e "${SetColor}Building containers.${EndColor}"
+echo -e "${SuccessColor}Generating ssh files.${EndColor}"
+openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes
+mv cert.pem ./.docker/nginx/
+mv key.pem ./.docker/nginx/
+
+echo -e "${SuccessColor}Building containers.${EndColor}"
 docker compose up -d
 
-bin/setup
+if [[ $? -ne 0 ]]; then
+    echo -e "${ErrorColor}Something went wrong creating the containers.${EndColor}"
+    exit
+fi
+
+echo -e "${SuccessColor}Running composer install.${EndColor}"
+bin/cli composer install
+
+echo -e "${SuccessColor}Installing Magento 2.${EndColor}"
+bin/cli bin/magento setup:install \
+--base-url=https://m2.localhost.com/ \
+--backend-frontname=admin \
+--db-host=db \
+--db-name=magento \
+--db-user=admin \
+--db-password=admin123 \
+--admin-firstname=Admin \
+--admin-lastname=Magento \
+--admin-email=admin@admin.com \
+--admin-user=admin \
+--admin-password=admin123 \
+--language=pt_BR \
+--currency=BRL \
+--timezone=America/Sao_Paulo \
+--use-rewrites=1 \
+--amqp-host=rabbitmq \
+--amqp-port=5672 \
+--amqp-user=magento \
+--amqp-password=magento \
+--search-engine=elasticsearch7 \
+--elasticsearch-host=elasticsearch \
+--elasticsearch-port=9200 \
+--cleanup-database
+
+if [[ $? -ne 0 ]]; then
+    echo -e "${ErrorColor}Something went wrong installing Magento 2.${EndColor}"
+    exit
+fi
+
+echo -e "${SuccessColor}Configuring developer mode.${EndColor}"
+bin/cli bin/magento deploy:mode:set developer
+bin/cli bin/magento module:disable {Magento_AdminAdobeImsTwoFactorAuth,Magento_TwoFactorAuth}
+
+echo -e "${SuccessColor}Configuring cache for Redis.${EndColor}"
+bin/cli bin/magento setup:config:set --cache-backend=redis \
+    --cache-backend-redis-server=redis \
+    --cache-backend-redis-port=6379 \
+    --cache-backend-redis-db=0
+bin/cli bin/magento setup:config:set --page-cache=redis \
+    --page-cache-redis-server=redis \
+    --page-cache-redis-db=1
+
+echo -e "${SuccessColor}Saving basic configs for Magento.${EndColor}"
+bin/cli bin/magento config:set system/security/max_session_size_admin 2560000
+bin/cli bin/magento config:set general/country/default BR
+bin/cli bin/magento config:set general/locale/weight_unit kgs
+bin/cli bin/magento config:set customer/captcha/enable 0
+bin/cli bin/magento config:set customer/captcha/forms NULL
+bin/cli bin/magento config:set customer/create_account/vat_frontend_visibility 1
+bin/cli bin/magento config:set customer/address/street_lines 4
+bin/cli bin/magento config:set customer/address/taxvat_show opt
+bin/cli bin/magento config:set admin/security/session_lifetime 31536000
+bin/cli bin/magento config:set admin/captcha/enable 0
+bin/cli bin/magento config:set admin/captcha/forms NULL
+bin/cli bin/magento config:set dev/debug/template_hints_storefront 1
+bin/cli bin/magento config:set dev/debug/template_hints_storefront_show_with_parameter 1
+bin/cli bin/magento config:set dev/debug/template_hints_parameter_value magento
+
+echo -e "${SuccessColor}Compiling Magento.${EndColor}"
+bin/cli bin/magento app:config:import
+bin/cli bin/magento setup:upgrade
+bin/cli bin/magento indexer:reindex
+bin/cli bin/magento setup:di:compile
+bin/cli bin/magento setup:static-content:deploy -f
+bin/cli bin/magento cache:clean
+bin/cli bin/magento cache:flush
